package genframework

import (
	"bytes"
	"fmt"
)

func genRegistration(cfg Config, resources []Resource) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen-tf; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)
	fmt.Fprintf(&b, "import (\n\t%q\n\t%q\n)\n\n",
		"github.com/hashicorp/terraform-plugin-framework/datasource",
		"github.com/hashicorp/terraform-plugin-framework/resource")
	fmt.Fprintf(&b, "// generatedResources lists every generated resource constructor.\n")
	fmt.Fprintf(&b, "func generatedResources() []func() resource.Resource {\n")
	fmt.Fprintf(&b, "\treturn []func() resource.Resource{\n")
	for _, r := range resources {
		fmt.Fprintf(&b, "\t\t%s,\n", r.ctor())
	}
	fmt.Fprintf(&b, "\t}\n}\n\n")
	fmt.Fprintf(&b, "// generatedDataSources lists every generated data source constructor.\n")
	fmt.Fprintf(&b, "func generatedDataSources() []func() datasource.DataSource {\n")
	fmt.Fprintf(&b, "\treturn []func() datasource.DataSource{\n")
	for _, r := range resources {
		fmt.Fprintf(&b, "\t\tNew%sDataSource,\n", r.Noun)
	}
	fmt.Fprintf(&b, "\t}\n}\n")
	return gofmt(b.String())
}

func genResource(cfg Config, r Resource) ([]byte, error) {
	var b bytes.Buffer
	recv := r.recv()
	model := r.model()
	svc := "r.client." + cfg.ClientField
	pkg := cfg.BindingsPkg

	fmt.Fprintf(&b, "// Code generated by gen-tf; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)

	// Imports — over-include is not an option (unused imports fail), so include
	// exactly what the body references.
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", "context")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/diag")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/path")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema")
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier")
	if r.hasBoolMod() {
		fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier")
	}
	if r.hasSet() {
		fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier")
	}
	fmt.Fprintf(&b, "\t%q\n", "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier")
	fmt.Fprintf(&b, "\t%q\n\n", "github.com/hashicorp/terraform-plugin-framework/types")
	fmt.Fprintf(&b, "\t%q\n", "github.com/philband/go-msadmin/consistency")
	fmt.Fprintf(&b, "\t%q\n", cfg.BindingsImport)
	fmt.Fprintf(&b, "\t%q\n", cfg.ClientsImport)
	fmt.Fprintf(&b, "\t%q\n", "github.com/philband/tf-msadmin/reconcile")
	fmt.Fprintf(&b, "\t%q\n", "github.com/philband/tf-msadmin/resourcex")
	fmt.Fprintf(&b, ")\n\n")

	// Interface asserts + type + constructor.
	fmt.Fprintf(&b, "var (\n")
	fmt.Fprintf(&b, "\t_ resource.Resource = &%s{}\n", recv)
	fmt.Fprintf(&b, "\t_ resource.ResourceWithConfigure = &%s{}\n", recv)
	fmt.Fprintf(&b, "\t_ resource.ResourceWithImportState = &%s{}\n", recv)
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "type %s struct{ client *clients.Client }\n\n", recv)
	fmt.Fprintf(&b, "// %s manages the %s object (%s / %s / %s / %s).\n",
		r.ctor(), r.Noun, r.cmdlet("New"), r.cmdlet("Get"), r.cmdlet("Set"), r.cmdlet("Remove"))
	fmt.Fprintf(&b, "func %s() resource.Resource { return &%s{} }\n\n", r.ctor(), recv)

	// Model.
	fmt.Fprintf(&b, "type %s struct {\n", model)
	fmt.Fprintf(&b, "\tID types.String `tfsdk:\"id\"`\n")
	fmt.Fprintf(&b, "\tIdentity types.String `tfsdk:\"identity\"`\n")
	for _, a := range r.Attributes {
		fmt.Fprintf(&b, "\t%s\n", a.modelField())
	}
	fmt.Fprintf(&b, "}\n\n")

	// Metadata.
	fmt.Fprintf(&b, "func (r *%s) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.TypeName = req.ProviderTypeName + %q\n}\n\n", "_"+r.TFName)

	// Schema.
	fmt.Fprintf(&b, "func (r *%s) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {\n", recv)
	fmt.Fprintf(&b, "\tresp.Schema = schema.Schema{\n")
	fmt.Fprintf(&b, "\t\tDescription: %q,\n", r.Description)
	fmt.Fprintf(&b, "\t\tAttributes: map[string]schema.Attribute{\n")
	fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},\n",
		"id", "Object identifier (GUID).")
	fmt.Fprintf(&b, "\t\t\t%q: schema.StringAttribute{Computed: true, Description: %q},\n",
		"identity", "Identity used to target the object in cmdlets.")
	for _, a := range r.Attributes {
		fmt.Fprintf(&b, "\t\t\t%q: %s,\n", a.TFName, a.schemaAttr())
	}
	fmt.Fprintf(&b, "\t\t},\n\t}\n}\n\n")

	// Configure.
	fmt.Fprintf(&b, "func (r *%s) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {\n", recv)
	fmt.Fprintf(&b, "\tif req.ProviderData == nil {\n\t\treturn\n\t}\n")
	fmt.Fprintf(&b, "\tr.client = req.ProviderData.(*clients.Client)\n}\n\n")

	genCreate(&b, cfg, r, recv, model, svc, pkg)
	genRead(&b, cfg, r, recv, model)
	genUpdate(&b, cfg, r, recv, model, svc, pkg)
	genDelete(&b, cfg, r, recv, model, svc, pkg)
	genImport(&b, recv)
	genHelpers(&b, cfg, r, recv, model, svc, pkg)

	return gofmt(b.String())
}

func genCreate(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar plan %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n\n")
	fmt.Fprintf(b, "\tp := %s.%s{\n", pkg, r.Create.Params)
	for _, a := range r.Attributes {
		if a.InCreate && !a.Object {
			fmt.Fprintf(b, "\t\t%s: %s,\n", a.Field, a.planValue())
		}
	}
	fmt.Fprintf(b, "\t}\n")
	// System.Object params are `any` fields: only set when non-empty so "" is
	// not marshalled as a value.
	for _, a := range r.Attributes {
		if a.InCreate && a.Object {
			fmt.Fprintf(b, "\tif v := plan.%s.ValueString(); v != \"\" {\n\t\tp.%s = v\n\t}\n", a.Field, a.Field)
		}
	}
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tres, err := %s.%s(ctx, p)\n", svc, r.Create.Method)
	fmt.Fprintf(b, "\tif err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", r.cmdlet("New")+" failed")
	fmt.Fprintf(b, "\tobj := firstObject(res.Value)\n")
	fmt.Fprintf(b, "\tif obj == nil {\n\t\tresp.Diagnostics.AddError(%q, %q)\n\t\treturn\n\t}\n", r.cmdlet("New")+" returned no object", "the cmdlet did not return the created object")
	fmt.Fprintf(b, "\tcfg := plan\n")
	fmt.Fprintf(b, "\tident := %s\n", r.identityReadExpr())
	fmt.Fprintf(b, "\tif !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {\n")
	fmt.Fprintf(b, "\t\tif resp.Diagnostics.HasError() {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(b, "\t\tread%s(ctx, obj, &plan)\n\t}\n", r.Noun)
	fmt.Fprintf(b, "\tr.reconcileState(&cfg, &plan)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)\n}\n\n")
}

func genRead(b *bytes.Buffer, cfg Config, r Resource, recv, model string) {
	fmt.Fprintf(b, "func (r *%s) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar state %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.State.Get(ctx, &state)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {\n")
	fmt.Fprintf(b, "\t\tif !resp.Diagnostics.HasError() {\n\t\t\tresp.State.RemoveResource(ctx)\n\t\t}\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &state)...)\n}\n\n")
}

func genUpdate(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar plan, state %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.State.Get(ctx, &state)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tid := r.identityOf(state)\n")
	fmt.Fprintf(b, "\tsp := %s.%s{}\n", pkg, r.Update.Params)
	if r.Update.IdentityField != "" {
		fmt.Fprintf(b, "\tsp.%s = id\n", r.Update.IdentityField)
	}
	for _, a := range r.Attributes {
		if !a.InUpdate {
			continue
		}
		if a.Object {
			fmt.Fprintf(b, "\tif v := plan.%s.ValueString(); v != \"\" {\n\t\tsp.%s = v\n\t}\n", a.Field, a.Field)
		} else {
			fmt.Fprintf(b, "\tsp.%s = %s\n", a.Field, a.planValue())
		}
	}
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif _, err := %s.%s(ctx, sp); err != nil {\n\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\treturn\n\t}\n", svc, r.Update.Method, r.cmdlet("Set")+" failed")
	fmt.Fprintf(b, "\tcfg := plan\n")
	// reflected predicate over string attributes that were updated.
	fmt.Fprintf(b, "\treflected := reconcile.ReflectsFields(map[string]types.String{\n")
	for _, a := range r.Attributes {
		if a.InUpdate && a.Type == TypeString {
			fmt.Fprintf(b, "\t\t%q: cfg.%s,\n", a.APIName, a.Field)
		}
	}
	fmt.Fprintf(b, "\t}, getString)\n")
	fmt.Fprintf(b, "\tr.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)\n")
	fmt.Fprintf(b, "\tr.reconcileState(&cfg, &plan)\n")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)\n}\n\n")
}

func genDelete(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	fmt.Fprintf(b, "func (r *%s) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {\n", recv)
	fmt.Fprintf(b, "\tvar state %s\n", model)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(req.State.Get(ctx, &state)...)\n")
	fmt.Fprintf(b, "\tif resp.Diagnostics.HasError() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(b, "\tif _, err := %s.%s(ctx, %s.%s{%s: r.identityOf(state)}); err != nil {\n", svc, r.Delete.Method, pkg, r.Delete.Params, r.Delete.IdentityField)
	fmt.Fprintf(b, "\t\tif !isNotFound(err) {\n\t\t\tresp.Diagnostics.AddError(%q, err.Error())\n\t\t}\n\t}\n}\n\n", r.cmdlet("Remove")+" failed")
}

func genImport(b *bytes.Buffer, recv string) {
	fmt.Fprintf(b, "func (r *%s) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {\n", recv)
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(%q), req.ID)...)\n", "id")
	fmt.Fprintf(b, "\tresp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(%q), req.ID)...)\n}\n\n", "identity")
}

func genHelpers(b *bytes.Buffer, cfg Config, r Resource, recv, model, svc, pkg string) {
	// identityOf
	fmt.Fprintf(b, "func (r *%s) identityOf(m %s) any {\n", recv, model)
	fmt.Fprintf(b, "\tif v := m.Identity.ValueString(); v != \"\" {\n\t\treturn v\n\t}\n")
	fmt.Fprintf(b, "\tif v := m.ID.ValueString(); v != \"\" {\n\t\treturn v\n\t}\n")
	if r.hasName() {
		fmt.Fprintf(b, "\treturn m.Name.ValueString()\n")
	} else {
		fmt.Fprintf(b, "\treturn \"\"\n")
	}
	fmt.Fprintf(b, "}\n\n")

	// refresh
	fmt.Fprintf(b, "func (r *%s) refresh(ctx context.Context, identity any, m *%s, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {\n", recv, model)
	fmt.Fprintf(b, "\tget := func(ctx context.Context) (map[string]any, bool, error) {\n")
	fmt.Fprintf(b, "\t\tres, gerr := %s.%s(ctx, %s.%s{%s: identity})\n", svc, r.Read.Method, pkg, r.Read.Params, r.Read.IdentityField)
	fmt.Fprintf(b, "\t\tif gerr != nil {\n\t\t\tif isNotFound(gerr) {\n\t\t\t\treturn nil, false, nil\n\t\t\t}\n\t\t\treturn nil, false, gerr\n\t\t}\n")
	fmt.Fprintf(b, "\t\to := firstObject(res.Value)\n\t\treturn o, o != nil, nil\n\t}\n")
	fmt.Fprintf(b, "\tobj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\tdiags.AddError(%q, err.Error())\n\t\treturn false\n\t}\n", r.cmdlet("Get")+" failed")
	fmt.Fprintf(b, "\tif !present {\n\t\treturn false\n\t}\n")
	fmt.Fprintf(b, "\tread%s(ctx, obj, m)\n\treturn true\n}\n\n", r.Noun)

	// read<Noun> maps a read-back object into the model; shared by the resource
	// and the data source.
	fmt.Fprintf(b, "func read%s(ctx context.Context, obj map[string]any, m *%s) {\n", r.Noun, model)
	fmt.Fprintf(b, "\tm.ID = types.StringValue(firstNonEmptyStr(getString(obj, %q), getString(obj, %q), getString(obj, %q)))\n", "Guid", "Id", "Identity")
	fmt.Fprintf(b, "\tm.Identity = types.StringValue(%s)\n", r.identityReadExpr())
	for _, a := range r.Attributes {
		fmt.Fprintf(b, "\t%s\n", a.readAssign())
	}
	fmt.Fprintf(b, "\t_ = ctx\n}\n\n")

	// reconcileState
	fmt.Fprintf(b, "func (r *%s) reconcileState(cfg, read *%s) {\n", recv, model)
	for _, a := range r.Attributes {
		fmt.Fprintf(b, "\tread.%s = reconcile.%s(cfg.%s, read.%s)\n", a.Field, a.keepFn(), a.Field, a.Field)
	}
	fmt.Fprintf(b, "}\n")
}
